# Generated by Django 5.0.2 on 2024-03-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_friendrequest_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
